# Generated by Django 3.2.7 on 2021-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDonate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Випка', max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('prefix', 'Префикс'), ('rank', 'Привилегия')], default='prefix', max_length=16, verbose_name='Тип')),
                ('command', models.TextField(default='/say Hello &player&!', verbose_name='Команда')),
                ('price', models.IntegerField(default=100, max_length=255, verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Донат-услуга',
                'verbose_name_plural': 'Донат-услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceDonateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_player', models.CharField(default='lomaka', max_length=255, verbose_name='Игрок')),
                ('status_pay', models.CharField(choices=[('wait', 'Ожидает'), ('done', 'Оплачено')], default='wait', max_length=16, verbose_name='Статус')),
                ('service_id', models.IntegerField(verbose_name='ID услуги')),
            ],
            options={
                'verbose_name': 'Статус оплаты',
                'verbose_name_plural': 'Статусы оплаты',
            },
        ),
    ]
