# Generated by Django 3.2.7 on 2021-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonatestatus',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Сумма в рублях'),
        ),
    ]
