# Generated by Django 3.2.7 on 2021-12-09 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0002_auto_20211209_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonatestatus',
            name='serviceId',
            field=models.IntegerField(default=0, max_length=255, verbose_name='ID услуги'),
            preserve_default=False,
        ),
    ]
