# Generated by Django 3.2.7 on 2021-12-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0002_servicedonatestatus_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonatestatus',
            name='user_id_bot',
            field=models.IntegerField(default=0, verbose_name='ID пользователя в боте'),
        ),
    ]
