# Generated by Django 3.2.7 on 2021-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0003_servicedonatestatus_user_id_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedonatestatus',
            name='user_id_bot',
            field=models.BigIntegerField(default=0, verbose_name='ID пользователя в боте'),
        ),
    ]
