# Generated by Django 3.2.7 on 2021-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0004_alter_servicedonatestatus_user_id_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedonatestatus',
            name='status_pay',
            field=models.CharField(choices=[('wait', 'Ожидает'), ('paid', 'Оплачено'), ('done', 'Завершено')], default='wait', max_length=16, verbose_name='Статус'),
        ),
    ]
