# Generated by Django 3.2.7 on 2021-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0005_alter_servicedonatestatus_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedonate',
            name='command',
            field=models.TextField(default='/say Hello %_player%_!', verbose_name='Команда'),
        ),
    ]
