# Generated by Django 3.2.7 on 2021-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0006_auto_20211209_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedonatestatus',
            name='service_id',
            field=models.IntegerField(verbose_name='ID услуги'),
        ),
    ]
