# Generated by Django 3.2.7 on 2021-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0008_auto_20211211_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonatestatus',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
