# Generated by Django 3.2.7 on 2021-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0011_servicedonatestatus_success_code_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonatestatus',
            name='bill_id',
            field=models.CharField(default=0, max_length=64, verbose_name='Bill ID'),
        ),
    ]
