# Generated by Django 3.2.7 on 2021-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0012_servicedonatestatus_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedonatestatus',
            name='bill_id',
            field=models.CharField(default=0, max_length=48, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='servicedonatestatus',
            name='success_code_pay',
            field=models.CharField(default=0, max_length=48, verbose_name='Код успеха'),
        ),
    ]
