# Generated by Django 3.2.7 on 2021-12-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0013_auto_20211213_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedonatestatus',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='servicedonatestatus',
            name='success_code_pay',
        ),
    ]
