# Generated by Django 3.2.7 on 2021-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0014_auto_20211213_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanInBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None, max_length=255, verbose_name='ID пользователя')),
                ('comment', models.IntegerField(default='Команда Zalupa решила что тебя нужно заблокировать.', max_length=255, verbose_name='Комментарий (Его получит пользователь при попытке воспользоваться ботом)')),
            ],
            options={
                'verbose_name': 'Бан',
                'verbose_name_plural': 'Бан-лист',
            },
        ),
    ]
