# Generated by Django 3.2.7 on 2021-12-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0015_baninbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baninbot',
            name='comment',
            field=models.TextField(default='Команда Zalupa решила что тебя нужно заблокировать.', verbose_name='Комментарий (Его получит пользователь при попытке воспользоваться ботом)'),
        ),
    ]
