# Generated by Django 3.2.7 on 2021-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0018_alter_baninbot_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baninbot',
            name='user_id',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='ID пользователя'),
        ),
    ]
