# Generated by Django 3.2.7 on 2021-12-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_zalupa', '0019_alter_baninbot_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonatestatus',
            name='bill_id',
            field=models.CharField(default=0, max_length=64, unique=True, verbose_name='Номер платежа QIWI (Bill ID)'),
        ),
    ]
